### ISSUE TITLE
Help with the scoreboard

### ISSUE THREAD

**Issue by NotCacha-arg** [MinusKube/Netherboard#11]
Hello good morning I had these problems with the scoreboard and I don't know how to fix them, the error is
[11:48:20 ERROR]: Could not pass event PlayerJoinEvent to cFFA v1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:272) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:156) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:800) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at fr.minuskube.netherboard.bukkit.BPlayerBoard.<clinit>(BPlayerBoard.java:19) ~[?:?]
        at fr.minuskube.netherboard.Netherboard.createBoard(Netherboard.java:47) ~[?:?]
        at fr.minuskube.netherboard.Netherboard.createBoard(Netherboard.java:33) ~[?:?]
        at me.notcacha.cffa.scoreboard.ScoreboardPlayer.onCreate(ScoreboardPlayer.java:25) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        ... 14 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        at fr.minuskube.netherboard.bukkit.BPlayerBoard.<clinit>(BPlayerBoard.java:19) ~[?:?]
        at fr.minuskube.netherboard.Netherboard.createBoard(Netherboard.java:47) ~[?:?]
        at fr.minuskube.netherboard.Netherboard.createBoard(Netherboard.java:33) ~[?:?]
        at me.notcacha.cffa.scoreboard.ScoreboardPlayer.onCreate(ScoreboardPlayer.java:25) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        ... 14 more
[11:48:21 INFO]: NotCacha[/127.0.0.1:63873] logged in with entity id 223 at ([world] 106.79864272858377, 72.0, 340.81969753510134)
[11:48:21 WARN]: [cFFA] Task #3 for cFFA v1.0 generated an exception
java.lang.NullPointerException
        at me.notcacha.cffa.scoreboard.ScoreboardPlayer.updateScoreboard(ScoreboardPlayer.java:38) ~[?:?]
        at me.notcacha.cffa.scoreboard.ScoreboardPlayer.lambda$0(ScoreboardPlayer.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[11:48:23 WARN]: [cFFA] Task #3 for cFFA v1.0 generated an exception
java.lang.NullPointerException
        at me.notcacha.cffa.scoreboard.ScoreboardPlayer.updateScoreboard(ScoreboardPlayer.java:38) ~[?:?]
        at me.notcacha.cffa.scoreboard.ScoreboardPlayer.lambda$0(ScoreboardPlayer.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[11:48:26 WARN]: [cFFA] Task #3 for cFFA v1.0 generated an exception
java.lang.NullPointerException
        at me.notcacha.cffa.scoreboard.ScoreboardPlayer.updateScoreboard(ScoreboardPlayer.java:38) ~[?:?]
        at me.notcacha.cffa.scoreboard.ScoreboardPlayer.lambda$0(ScoreboardPlayer.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by MinusKube** [comment]
Mhh that's weird, what Spigot version are you using?

**Comment by NotCacha-arg** [comment]
Poor version 1.8.8 and the same thing happened to me and now I'm with 1.8
and paos the same

**Comment by NotCacha-arg** [comment]
What version do you recommend?

**Comment by NotCacha-arg** [comment]
You say it is the version of spigot ?, I have imported the core and the bukkit so as not to have to use the .jar but the same with the .jar does not work either deactivates the plugin

**Comment by MinusKube** [comment]
The version of Spigot is not a problem, here you'll need to add the SLF4J lib to your jar.
Example for Gradle (then export using shadowJar for instance):
```groovy
compile 'org.slf4j:slf4j-api:1.7.25'
compile 'org.slf4j:slf4j-simple:1.7.25'
```
Or you can also use the [provided Netherboard plugin](https://github.com/MinusKube/Netherboard/releases) (but you say the plugin gets deactivated? Can you check the console for errors?)

Also, if you don't want to add SLF4J into your jar nor to use the provided Netherboard plugin, you can remove the loggers from the BPlayerBoard and NMS classes manually.

**Comment by NotCacha-arg** [comment]
If I use the api with the .jar without the src if it works but if I
want to use the src to not use the .jar because it is a plugin for
spigot it gives me the error that I showed you before, and I am new to
the topic of java

**Comment by NotCacha-arg** [comment]
https://pastebin.com/NJqRvvrx :(

**Comment by MinusKube** [comment]
When you use the sources, you'll need to export the SLF4J dependencies inside your jar. With Gradle, you can use the [Shadow Plugin](https://imperceptiblethoughts.com/shadow/).
