### ISSUE TITLE
NPE on 1.13.2

### ISSUE THREAD

**Issue by Pugabyte** [MinusKube/Netherboard#3]
```
[14:33:37] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sb' in plugin BNCore v1.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-a1f2566-8cd538e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot.jar:git-Spigot-a1f2566-8cd538e]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[spigot.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[spigot.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-a1f2566-8cd538e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-a1f2566-8cd538e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
	at fr.minuskube.netherboard.bukkit.BPlayerBoard.sendObjective(BPlayerBoard.java:128) ~[?:?]
	at fr.minuskube.netherboard.bukkit.BPlayerBoard.<init>(BPlayerBoard.java:65) ~[?:?]
	at fr.minuskube.netherboard.Netherboard.createBoard(Netherboard.java:47) ~[?:?]
	at fr.minuskube.netherboard.Netherboard.createBoard(Netherboard.java:33) ~[?:?]
	at me.pugabyte.bncore.features.scoreboards.ScoreboardsCommand.onCommand(ScoreboardsCommand.java:34) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-a1f2566-8cd538e]
	... 15 more
```

```BPlayerBoard board = Netherboard.instance().createBoard(player, "Bear Nation");```

![image](https://user-images.githubusercontent.com/12417961/48958510-86447400-ef2d-11e8-8af3-523901a09172.png)

**Comment by MinusKube** [comment]
And here it is, fixed in 1.1.0 :)
