### ISSUE TITLE
PlayBoard did not loads(?)

### ISSUE THREAD

**Issue by RedrixOne** [MinusKube/netherboard#48]
I done a Minecraft (1.8) plugin that generates a Scoreboard with some basically player informations (I built it with Maven and the API won't show any errors), but at the moment that i have to build the plugin the console shows me an error like he can't reach the PlayerBoard's API, can anyone help me?

**Comment by RedrixOne** [comment]
UPDATE: I loaded netherboard-core and it works, but in console i have that error:

Task #2 for StrawPvP v1.0 generated an exception
java.lang.NoClassDefFoundError: fr/minuskube/netherboard/Netherboard
        at com.redrixone.scoreboard.Scoreboard.updateScoreboard(Scoreboard.java:46) ~[?:?]
        at com.redrixone.scoreboard.Scoreboard$1.run(Scoreboard.java:38) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by RedrixOne** [comment]
Solved i'm so stupid and i didn't add the jar in my plugins folder, btw thanks ^^
