### ISSUE TITLE
java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.ScoreboardServer$Action

### ISSUE THREAD

**Issue by MrJanek** [MinusKube/Netherboard#5]
Hi, i have an issue with API (Maven) this is it:
`[13:08:32] [Server thread/WARN]: [Server thread] ERROR fr.minuskube.netherboard.bukkit.util.NMS - Error while loading NMS methods. (Unsupported Minecraft version?)
[13:08:32] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.ScoreboardServer$Action
[13:08:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[13:08:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[13:08:32] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[13:08:32] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[13:08:32] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[13:08:32] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[13:08:32] [Server thread/WARN]: 	at fr.minuskube.netherboard.bukkit.util.NMS.getClass(NMS.java:139)
[13:08:32] [Server thread/WARN]: 	at fr.minuskube.netherboard.bukkit.util.NMS.<clinit>(NMS.java:70)
[13:08:32] [Server thread/WARN]: 	at fr.minuskube.netherboard.bukkit.BPlayerBoard.sendObjective(BPlayerBoard.java:129)
[13:08:32] [Server thread/WARN]: 	at fr.minuskube.netherboard.bukkit.BPlayerBoard.<init>(BPlayerBoard.java:65)
[13:08:32] [Server thread/WARN]: 	at fr.minuskube.netherboard.Netherboard.createBoard(Netherboard.java:47)
[13:08:32] [Server thread/WARN]: 	at fr.minuskube.netherboard.Netherboard.createBoard(Netherboard.java:33)
[13:08:32] [Server thread/WARN]: 	at pl.jms.grupowetp.Main.showSidebar(Main.java:54)
[13:08:32] [Server thread/WARN]: 	at pl.jms.grupowetp.pl.jms.grupowetp.listeners.PlayerJoinListener.onJoin(PlayerJoinListener.java:27)
[13:08:32] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:08:32] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:08:32] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:08:32] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:08:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[13:08:32] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:08:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[13:08:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[13:08:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[13:08:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[13:08:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[13:08:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[13:08:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[13:08:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[13:08:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814)
[13:08:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[13:08:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[13:08:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[13:08:32] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
`

**Comment by MinusKube** [comment]
Oh, thank you for the report, I'll fix this asap. This is an issue with the last version, if you take the version 1.0.6, it should work correctly :)

**Comment by MrJanek** [comment]
But i have version 1.0.6
        <dependency>
            <groupId>fr.minuskube</groupId>
            <artifactId>netherboard-bukkit</artifactId>
            <version>1.0.6</version>
        </dependency>
But now i look at logs and it now give me Null on buffer
`Caused by: java.lang.NullPointerException
	at fr.minuskube.netherboard.bukkit.BPlayerBoard.sendObjective(BPlayerBoard.java:131) ~[?:?]
	at fr.minuskube.netherboard.bukkit.BPlayerBoard.<init>(BPlayerBoard.java:65) ~[?:?]
	at fr.minuskube.netherboard.Netherboard.createBoard(Netherboard.java:47) ~[?:?]
	at pl.jms.grupowetp.Main.showSidebar(Main.java:57) ~[?:?]
	at pl.jms.grupowetp.pl.jms.grupowetp.listeners.PlayerJoinListener.onJoin(PlayerJoinListener.java:27) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[mc.jar:git-Spigot-21fe707-e1ebe52]
	... 14 more
`

**Comment by MrJanek** [comment]
@MinusKube

**Comment by MrJanek** [comment]
@MinusKube 
Please answer I need api to finish the plugin

**Comment by MrJanek** [comment]
1. I use 1.8.8
2. I checked and this version i based on Netherboard 1.0.6

**Comment by MinusKube** [comment]
I just checked and this problem only happen in Netherboard 1.1.0 due to the "ScoreboardServer$Action" not being found.

**Comment by MrJanek** [comment]
Hmm ;/

**Comment by MinusKube** [comment]
Yeah, just make sure you respect the license :p https://github.com/MinusKube/Netherboard/blob/master/LICENSE

**Comment by MinusKube** [comment]
Yeah, just make sure you respect the license :p https://github.com/MinusKube/Netherboard/blob/master/LICENSE

**Comment by MinusKube** [comment]
Fixed in 1.1.1! :)
